### ISSUE TITLE
Tradeable non-GE items not being marked as tradeable

### ISSUE THREAD

**Issue by MichaelTheriot** [villermen/runescape-cache-tools#82]
I noticed items that cannot be exchanged on the GE, but are tradeable, are not marked as tradeable.

```json
{
  "modelId": 47840,
  "name": "Marker seeds",
  "modelZoom": 1104,
  "modelRotation1": 255,
  "modelRotation2": 120,
  "value": 65,
  "inventoryOption1": "Plant-marker",
  "inventoryOption2": "Directional-marker",
  "noteId": 15076,
  "unknown113": 15,
  "unknown114": 5,
  "unknown144": 45
}
```

Is this information not available in the cache or is it just being misinterpreted?

**Comment by villermen** [comment]
Thanks for reporting! I'd imagine whether an item is tradeable is more likely to be a property than whether it's exchangeable. So it's most likely a misinterpretation. Maybe it means whether it can be noted? Either way, I'll look into it soon™

**Comment by villermen** [comment]
Based on below information it seems like "tradeable" is indeed not the correct term here. As far as I can tell it does seem to hold true for all exchangeable items though. I could rename it to "exchangeable". Can you think/find any items that this wouldn't hold for? @MichaelTheriot 

I've also identified some properties related to trade restricted items (items that can only be traded manually for equal amounts of items in the same category). These do not have the tradeable flag in RSCT right now but definitely _are_ tradeable in some way.

Maybe it's related to whether items can be noted or not? That's probably why the listed absorption boots are noteable too. This however doesn't hold for extreme potions which can be noted but not traded... What I do know is that it's a messy situation however we look at it.

---

```
marker seeds (tradeable, non-ge):
    unknown113: 15
    unknown114: 5
    unknown144: 45

summer pie (tradeable):
    unknown113: 10
    unknown114: 10
    unknown144: 45

dried chillies (restricted trade, non-ge):
    unknown144: 45
    properties:
        unknown3741: 1
        unknown689: 1
        unknown1397: 2
        unknown4907: 125 (destroyForGp)

pure caffeine (restricted trade, same set as dried chillies):
    unknown144: 45
    properties:
        unknown3741: 1
        unknown689: 1
        unknown1397: 2
        unknown4907: 125

tuska mask plate (restricted trade):
    unknown113: 30
    unknown144: 45
    properties:
        unknown1397: 1
        unknown689: 1
        unknown31: 1
        unknown3741: 1

coffee stroopwafel (restricted trade):
    unknown144: 45
    unknown150: 47
    properties:
        unknown31: 1
        unknown3324: 1
        unknown689: 1
        unknown2951: 10
        unknown3741: 1
```

```json
// tradeable
{
    "id": 17281,
    "modelId": 54155,
    "name": "Absorption boots",
    "modelZoom": 855,
    "modelRotation1": 158,
    "modelRotation2": 246,
    "modelOffset1": 5,
    "modelOffset2": -7,
    "value": 3500,
    "equipSlot": 10,
    "membersOnly": true,
    "maleEquip1": 55692,
    "femaleEquip1": 56376,
    "inventoryOption2": "Wear",
    "inventoryOption3": "Bind",
    "category": 17,
    "noteId": 17282,
    "unknown144": 45,
    "unknown151": 51,
    "properties": {
        "unknown2822": 1,
        "magicAffinity": 45,
        "meleeAffinity": 65,
        "rangedAffinity": 55,
        "armourBonus": 520,
        "unknown118": 7197,
        "dropSoundId": 4191,
        "unknown1046": 125,
        "equipSkillRequired": 4,
        "equipLevelRequired": 57,
        "equipSkillRequired2": 1,
        "equipLevelRequired2": 57,
        "unknown1047": 1
    }
}
// untradeable
{
    "id": 15829,
    "modelId": 54155,
    "name": "Absorption boots (b)",
    "modelZoom": 855,
    "modelRotation1": 158,
    "modelRotation2": 246,
    "modelOffset1": 5,
    "modelOffset2": -7,
    "value": 0,
    "equipSlot": 10,
    "unknown15": true,
    "membersOnly": true,
    "maleEquip1": 55692,
    "femaleEquip1": 56376,
    "inventoryOption2": "Wear",
    "inventoryOption5": "Destroy",
    "category": 17,
    "unknown144": 45,
    "unknown151": 51,
    "properties": {
        "unknown2822": 1,
        "magicAffinity": 45,
        "meleeAffinity": 65,
        "rangedAffinity": 55,
        "armourBonus": 520,
        "unknown118": 7191,
        "unknown1046": 125,
        "equipSkillRequired": 4,
        "equipLevelRequired": 57,
        "equipSkillRequired2": 1,
        "equipLevelRequired2": 57,
        "unknown31": 1,
        "unknown1047": 1,
        "unknown1050": 1,
        "unknown689": 1
    }
}
// non-tradeable, noteable
{
    "id": 15320,
    "modelId": 2789,
    "name": "Extreme magic (4)",
    "modelZoom": 550,
    "modelRotation1": 84,
    "modelRotation2": 1996,
    "modelOffset2": -1,
    "value": 275,
    "unknown15": true,
    "membersOnly": true,
    "inventoryOption1": "Drink",
    "inventoryOption4": "Empty",
    "modelColors": [[61],[33490]],
    "category": 69,
    "noteId": 26624,
    "unknown144": 45,
    "unknown150": 48,
    "properties": {
        "beastOfBurdenStorable": 1,
        "unknown3744": 1,
        "dropSoundId": 4175,
        "unknown2281": 278
    }
}
```
